const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),store=require('./lib/store');
const PORT=process.env.PORT||3000,PUBLIC=path.join(__dirname,'public');
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.webp':'image/webp','.ico':'image/x-icon','.woff2':'font/woff2'};
const db=()=>store.read('whatssnap',{users:[],sessions:[],friendships:[],requests:[],chats:[],messages:[],stories:[],spotlights:[],reports:[],calls:[]});
const put=d=>store.write('whatssnap',d);const id=()=>crypto.randomUUID();
function json(res,data,status=200){let p=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json','Content-Length':Buffer.byteLength(p)});res.end(p)}
function body(req){return new Promise((ok,no)=>{let r='';req.on('data',c=>{r+=c;if(r.length>8e6){req.destroy();no(Error('Too large'))}});req.on('end',()=>{try{ok(r?JSON.parse(r):{})}catch{no(Error('Invalid JSON'))}});req.on('error',no)})}
function hash(password,salt=crypto.randomBytes(16).toString('hex')){return{salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function auth(req,d){let token=(req.headers.authorization||'').replace(/^Bearer /,'');let s=d.sessions.find(x=>x.token===token);return s&&d.users.find(x=>x.id===s.userId)}
function safeUser(u){return{id:u.id,username:u.username,display:u.display||u.username,bio:u.bio||'',avatar:u.avatar||'',privacy:u.privacy||{messages:'friends',calls:'friends',stories:'friends'}}}
function streakFor(c,msgs){if(c.type!=='direct')return 0;let days=new Map;msgs.filter(m=>m.type==='image').forEach(m=>{let day=new Date(m.created).toISOString().slice(0,10);if(!days.has(day))days.set(day,new Set);days.get(day).add(m.userId)});let cursor=new Date();let today=cursor.toISOString().slice(0,10);if((days.get(today)?.size||0)<2)cursor.setUTCDate(cursor.getUTCDate()-1);let count=0;while(true){let day=cursor.toISOString().slice(0,10);if((days.get(day)?.size||0)<2)break;count++;cursor.setUTCDate(cursor.getUTCDate()-1)}return count}
function myChats(d,u){return d.chats.filter(c=>c.members.includes(u.id)).map(c=>{let users=c.members.filter(x=>x!==u.id).map(x=>safeUser(d.users.find(y=>y.id===x)));let msgs=d.messages.filter(m=>m.chatId===c.id);return{...c,users,last:msgs.at(-1)||null,streak:streakFor(c,msgs)}})}
const routes={
'POST /api/register':async(req,res)=>{let x=await body(req),d=db(),username=String(x.username||'').toLowerCase().trim();if(!/^[a-z0-9_]{3,18}$/.test(username)||String(x.password||'').length<6)return json(res,{error:'Use a valid username and a 6+ character password'},400);if(d.users.some(u=>u.username===username))return json(res,{error:'Username is taken'},409);let h=hash(x.password),recovery=crypto.randomBytes(6).toString('hex').toUpperCase(),rh=hash(recovery),u={id:id(),username,display:username,bio:'',avatar:'',privacy:{messages:'friends',calls:'friends',stories:'friends'},blocked:[],recoverySalt:rh.salt,recoveryHash:rh.hash,...h},token=crypto.randomBytes(32).toString('hex');d.users.push(u);d.sessions.push({token,userId:u.id});put(d);json(res,{token,user:safeUser(u),recovery},201)},
'POST /api/login':async(req,res)=>{let x=await body(req),d=db(),u=d.users.find(v=>v.username===String(x.username||'').toLowerCase());if(!u||hash(x.password,u.salt).hash!==u.hash)return json(res,{error:'Incorrect username or password'},401);let token=crypto.randomBytes(32).toString('hex');d.sessions.push({token,userId:u.id});put(d);json(res,{token,user:safeUser(u)})},
'GET /api/sync':(req,res)=>{let d=db(),u=auth(req,d);if(!u)return json(res,{error:'Sign in required'},401);d.requests??=[];d.calls??=[];let chats=myChats(d,u),ids=new Set(chats.map(c=>c.id)),stories=d.stories.filter(s=>Date.now()-s.created<86400000&&s.userId!==u.id&&!u.blocked?.includes(s.userId)).map(s=>({...s,user:safeUser(d.users.find(x=>x.id===s.userId))}));d.messages.filter(m=>ids.has(m.chatId)&&m.userId!==u.id).forEach(m=>{m.deliveredTo??=[];m.seenBy??=[];if(!m.deliveredTo.includes(u.id))m.deliveredTo.push(u.id)});put(d);json(res,{user:safeUser(u),friends:d.friendships.filter(f=>f.includes(u.id)).map(f=>safeUser(d.users.find(x=>x.id===f.find(y=>y!==u.id)))),requests:d.requests.filter(r=>r.to===u.id).map(r=>({...r,user:safeUser(d.users.find(x=>x.id===r.from))})),chats,messages:d.messages.filter(m=>ids.has(m.chatId)),stories,calls:d.calls.filter(c=>c.members.includes(u.id)).slice(-20).reverse()})},
'POST /api/friends':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d);d.requests??=[];if(!u)return json(res,{error:'Sign in required'},401);let other=d.users.find(v=>v.username===String(x.username||'').toLowerCase());if(!other||other.id===u.id||other.blocked?.includes(u.id))return json(res,{error:'Username not found'},404);if(!d.requests.some(r=>r.from===u.id&&r.to===other.id))d.requests.push({id:id(),from:u.id,to:other.id,created:Date.now()});put(d);json(res,{requested:true},201)},
'POST /api/friends/respond':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d),r=(d.requests||[]).find(v=>v.id===x.id&&v.to===u?.id);if(!r)return json(res,{error:'Request not found'},404);if(x.accept){d.friendships.push([r.from,r.to]);d.chats.push({id:id(),type:'direct',name:'',members:[r.from,r.to],created:Date.now()})}d.requests=d.requests.filter(v=>v.id!==r.id);put(d);json(res,{ok:true})},
'POST /api/groups':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d);if(!u)return json(res,{error:'Sign in required'},401);let members=[...new Set([u.id,...(x.members||[])])];if(members.length<3)return json(res,{error:'Choose at least two friends'},400);let c={id:id(),type:'group',name:String(x.name||'Group').slice(0,30),members,created:Date.now()};d.chats.push(c);put(d);json(res,c,201)},
'POST /api/messages':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d),c=d.chats.find(v=>v.id===x.chatId);if(!u||!c?.members.includes(u.id))return json(res,{error:'Not allowed'},403);let m={id:id(),chatId:c.id,userId:u.id,type:x.type==='image'?'image':'text',text:String(x.text||'').slice(0,2000),data:x.type==='image'?String(x.data||''):'',created:Date.now(),seenBy:[u.id]};d.messages.push(m);put(d);json(res,m,201)},
'POST /api/messages/seen':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d),c=d.chats.find(v=>v.id===x.chatId);if(!u||!c?.members.includes(u.id))return json(res,{error:'Not allowed'},403);d.messages.filter(m=>m.chatId===c.id).forEach(m=>{m.seenBy??=[];if(!m.seenBy.includes(u.id))m.seenBy.push(u.id)});put(d);json(res,{ok:true})},
'POST /api/stories':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d);if(!u)return json(res,{error:'Sign in required'},401);let s={id:id(),userId:u.id,data:String(x.data||''),created:Date.now()};d.stories.push(s);put(d);json(res,s,201)},
'PATCH /api/profile':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d);if(!u)return json(res,{error:'Sign in required'},401);u.display=String(x.display||u.username).slice(0,30);u.bio=String(x.bio||'').slice(0,100);if(x.avatar)u.avatar=String(x.avatar);put(d);json(res,safeUser(u))},
'PATCH /api/privacy':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d);if(!u)return json(res,{error:'Sign in required'},401);u.privacy={messages:x.messages==='everyone'?'everyone':'friends',calls:x.calls==='nobody'?'nobody':'friends',stories:x.stories==='everyone'?'everyone':'friends'};put(d);json(res,u.privacy)},
'POST /api/block':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d),other=d.users.find(v=>v.id===x.userId);if(!u||!other)return json(res,{error:'User not found'},404);u.blocked??=[];if(!u.blocked.includes(other.id))u.blocked.push(other.id);d.friendships=d.friendships.filter(f=>!(f.includes(u.id)&&f.includes(other.id)));put(d);json(res,{ok:true})},
'POST /api/report':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d);if(!u)return json(res,{error:'Sign in required'},401);d.reports??=[];d.reports.push({id:id(),from:u.id,targetId:x.targetId,type:x.type||'user',reason:String(x.reason||'Safety concern').slice(0,200),created:Date.now()});put(d);json(res,{ok:true},201)},
'GET /api/export':(req,res)=>{let d=db(),u=auth(req,d);if(!u)return json(res,{error:'Sign in required'},401);let chatIds=d.chats.filter(c=>c.members.includes(u.id)).map(c=>c.id);json(res,{profile:safeUser(u),friends:d.friendships.filter(f=>f.includes(u.id)),chats:d.chats.filter(c=>chatIds.includes(c.id)),messages:d.messages.filter(m=>chatIds.includes(m.chatId)),stories:d.stories.filter(s=>s.userId===u.id),spotlights:(d.spotlights||[]).filter(s=>s.userId===u.id)})},
'DELETE /api/account':async(req,res)=>{let d=db(),u=auth(req,d);if(!u)return json(res,{error:'Sign in required'},401);d.users=d.users.filter(x=>x.id!==u.id);d.sessions=d.sessions.filter(x=>x.userId!==u.id);d.friendships=d.friendships.filter(f=>!f.includes(u.id));d.requests=(d.requests||[]).filter(r=>r.from!==u.id&&r.to!==u.id);d.chats=d.chats.filter(c=>!c.members.includes(u.id));d.messages=d.messages.filter(m=>m.userId!==u.id);d.stories=d.stories.filter(s=>s.userId!==u.id);d.spotlights=(d.spotlights||[]).filter(s=>s.userId!==u.id);put(d);json(res,{ok:true})},
'GET /api/moderation':(req,res)=>{let d=db(),u=auth(req,d);if(!u||u.username!==process.env.ADMIN_USERNAME)return json(res,{error:'Admin access required'},403);json(res,{reports:d.reports||[],users:d.users.map(safeUser),spotlights:d.spotlights||[]})},
'POST /api/moderation/action':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d);if(!u||u.username!==process.env.ADMIN_USERNAME)return json(res,{error:'Admin access required'},403);if(x.action==='hide') {let v=(d.spotlights||[]).find(s=>s.id===x.id);if(v)v.hidden=true}if(x.action==='suspend'){let v=d.users.find(s=>s.id===x.id);if(v)v.suspended=true}put(d);json(res,{ok:true})},
'POST /api/calls':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d),c=d.chats.find(v=>v.id===x.chatId);if(!u||!c?.members.includes(u.id))return json(res,{error:'Not allowed'},403);d.calls??=[];let call={id:id(),chatId:c.id,members:c.members,startedBy:u.id,type:x.type==='video'?'video':'audio',created:Date.now(),status:'started'};d.calls.push(call);put(d);json(res,call,201)},
'POST /api/recover':async(req,res)=>{let x=await body(req),d=db(),u=d.users.find(v=>v.username===String(x.username||'').toLowerCase());if(!u||!u.recoveryHash||hash(String(x.code||'').toUpperCase(),u.recoverySalt).hash!==u.recoveryHash||String(x.password||'').length<6)return json(res,{error:'Recovery details are incorrect'},400);let h=hash(x.password);u.salt=h.salt;u.hash=h.hash;d.sessions=d.sessions.filter(s=>s.userId!==u.id);put(d);json(res,{ok:true})},
'GET /api/spotlight':(req,res)=>{let d=db(),u=auth(req,d);if(!u)return json(res,{error:'Sign in required'},401);d.spotlights??=[];json(res,d.spotlights.filter(v=>!v.hidden&&!u.blocked?.includes(v.userId)).slice().reverse().map(v=>({...v,user:safeUser(d.users.find(x=>x.id===v.userId)),liked:v.likes.includes(u.id)})))},
'POST /api/spotlight':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d);if(!u)return json(res,{error:'Sign in required'},401);if(!String(x.data||'').startsWith('data:video/'))return json(res,{error:'Choose a video'},400);d.spotlights??=[];let v={id:id(),userId:u.id,data:String(x.data),caption:String(x.caption||'').slice(0,120),created:Date.now(),likes:[]};d.spotlights.push(v);put(d);json(res,{...v,user:safeUser(u),liked:false},201)},
'POST /api/spotlight/like':async(req,res)=>{let x=await body(req),d=db(),u=auth(req,d),v=(d.spotlights||[]).find(y=>y.id===x.id);if(!u||!v)return json(res,{error:'Video not found'},404);v.likes.includes(u.id)?v.likes=v.likes.filter(y=>y!==u.id):v.likes.push(u.id);put(d);json(res,{likes:v.likes.length,liked:v.likes.includes(u.id)})},
'POST /api/logout':(req,res)=>{let d=db(),token=(req.headers.authorization||'').replace(/^Bearer /,'');d.sessions=d.sessions.filter(s=>s.token!==token);put(d);json(res,{ok:true})}}
function sendFile(res,file,data){res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream'});res.end(data)}
function serve(req,res,pathname){let rel=pathname==='/'?'index.html':decodeURIComponent(pathname).replace(/^\/+/,''),file=path.join(PUBLIC,rel);if(file!==PUBLIC&&!file.startsWith(PUBLIC+path.sep))return json(res,{error:'Not found'},404);fs.readFile(file,(e,data)=>{if(!e)return sendFile(res,file,data);if(path.extname(rel))return json(res,{error:'Not found'},404);fs.readFile(path.join(PUBLIC,'index.html'),(x,h)=>x?json(res,{error:'Not found'},404):sendFile(res,path.join(PUBLIC,'index.html'),h))})}
http.createServer(async(req,res)=>{let pathname='/';try{pathname=new URL(req.url,`http://${req.headers.host||'localhost'}`).pathname;let fn=routes[`${req.method} ${pathname}`];fn?await fn(req,res):serve(req,res,pathname)}catch(e){console.error(e);if(!res.headersSent)json(res,{error:e.message||'Server error'},500)}}).listen(PORT,'0.0.0.0',()=>console.log(`Listening on port ${PORT}`));
